identifier-prefix: ogc.geosparql.

name: GeoSPARQL
abstract: Building blocks for implementation of OGC GeoSPARQL using the OGC GeoSPARQL ontology and query language
description: |
  Each building block defines a reusable JSON schema that is mapped to the equivalent GeoSPARQL concept.
  
  Each fragment allows for transparent and validatable use of JSON-LD contexts to map schema elements to equivalent terms from the GeoSPARQL ontology. 
  
   _These components are under review by the GeoSPARQL SWG as candidate canonical implementations._ 
  
   Each building block allows for examples transformed to RDF, which in turn allows for the use of SHACL rules to enforce the semantics of the GeoSPARQL specifications.

schema-mapping:
  default: https://opengeospatial.github.io/bblocks/annotated-schemas/

imports:
  - default