name: Ontology Documentation CI

on: 
  push: 
      branches:
          - master
jobs:
  
  build:

    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Create Ontology Documentation ðŸ”§
      run: |
         sudo apt-get install python3 python3-setuptools python3-pip -y
         sudo apt-get install gcc libpq-dev -y
         sudo apt-get install python3-dev python3-pip -y
         sudo apt-get install asciidoctor ruby -y   
         sudo gem install --pre asciidoctor-pdf
         # sudo gem install metanorma-cli
         # sudo gem install metanorma-ogc
         sudo apt-get install python3-venv python3-wheel -y
         sudo pip3 install wheel pylode==2.13.2 rdflib
         mkdir docs
         mkdir docs/geosparql11/
         mkdir docs/geosparql10/
         mkdir docs/bestpractice/
         cp index.html docs/index.html
         cd docs/geosparql10/
         mkdir servicedescription
         cp ../../1.0/geo.ttl ../../1.0/profile.ttl ../../1.0/funcsrules.ttl ../../1.0/sf_geometries.ttl ../../1.0/11-052r4_OGC_GeoSPARQL.pdf ../../1.0/citeme.bib . 
         cp ../../1.0/servicedescription_allfunctions.ttl ../../1.0/servicedescription_conformanceclasses.ttl ../../1.0/servicedescription_extensions.ttl  . 
         echo "Generating documentation for GeoSPARQL 1.0 ontology"
         pylode -i ../../1.0/geo.ttl -o index.html
         python3 ../../convertjsonld.py geo.ttl geo.json
         echo "Generating documentation for GeoSPARQL 1.0 profile"
         pylode -i ../../1.0/profile.ttl -o profile.html -p prof
         echo "Generating documentation for GeoSPARQL 1.0 functions and rules"
         pylode -i ../../1.0/funcsrules.ttl -o funcsrules.html -p vocpub
         python3 ../../convertjsonld.py funcsrules.ttl funcsrules.json
         echo "Generating documentation for GeoSPARQL 1.0 Simple Features Vocabulary"
         pylode -i ../../1.0/sf_geometries.ttl -o sf_geometries.html -p vocpub
         python3 ../../convertjsonld.py sf_geometries.ttl sf_geometries.json
         # pylode -u http://schemas.opengis.net/gml/3.2.1/gml_32_geometries.rdf -o gml_geometries.html -p vocpub
         echo "Generating documentation for GeoSPARQL 1.0 Service Description Extensions"
         pylode -i ../../1.0/servicedescription_extensions.ttl -o servicedescription_extensions.html -p vocpub
         python3 ../../convertjsonld.py servicedescription_extensions.ttl servicedescription_extensions.json
         echo "Generating documentation for GeoSPARQL 1.0 Service Description Conformance Classes"
         pylode -i ../../1.0/servicedescription_conformanceclasses.ttl -o servicedescription_conformanceclasses.html -p vocpub
         python3 ../../convertjsonld.py servicedescription_conformanceclasses.ttl servicedescription_conformanceclasses.json
         echo "Generating documentation for GeoSPARQL 1.0 Service Description All Functions"
         pylode -i ../../1.0/servicedescription_allfunctions.ttl -o servicedescription_all_functions.html -p vocpub
         python3 ../../convertjsonld.py servicedescription_allfunctions.ttl servicedescription_all_functions.json
         cd ../geosparql11/
         mkdir servicedescription
         echo "Generating GeoSPARQL 1.1 Specification - ASCIIDOC HTML"
         asciidoctor --attribute docinfo=shared ../../1.1/spec/00-GeoSPARQL.adoc -o spec.html
         # echo "Generating GeoSPARQL 1.1 Specification ISO"
         # metanorma --type ogc  --extensions pdf,html ../../1.1/spec/00-GeoSPARQL.adoc
         echo "Generating GeoSPARQL 1.1 Specification - ASCIIDOC PDF"
         asciidoctor-pdf -a pdf-theme=default-with-fallback-font --attribute docinfo=shared ../../1.1/spec/00-GeoSPARQL.adoc -o spec.pdf
         echo "Generating GeoSPARQL 1.1 Release Notes - ASCIIDOC HTML"
         asciidoctor --attribute docinfo=shared ../../1.1/release_notes/releasenotes.adoc -o releasenotes.html
         # echo "Generating GeoSPARQL 1.1 Release Notes - ASCIIDOC PDF"
         # asciidoctor-pdf --attribute docinfo=shared ../../1.1/release_notes/releasenotes.adoc -o releasenotes.pdf
         echo "Copying over 1.1 RDF files"
         cp ../../1.1/geo.ttl ../../1.1/profile.ttl ../../1.1/funcsrules.ttl ../../1.1/sf_geometries.ttl ../../1.1/reqs.ttl  ../../1.1/spec/citeme.bib .
         cp ../../1.1/servicedescription/servicedescription_all_functions.ttl ../../1.1/servicedescription/servicedescription_conformanceclasses.ttl ../../1.1/servicedescription/servicedescription_extensions.ttl .
         # ../../1.1/validation.ttl
         cp -r ../../1.1/spec/img .
         echo "Generating documentation for GeoSPARQL 1.1 ontology"
         python3 ../../convertjsonld.py geo.ttl geo.json
         pylode -i ../../1.1/geo.ttl -o index.html
         echo "Generating documentation for GeoSPARQL 1.1 Profile"
         pylode -i ../../1.1/profile.ttl -o profile.html -p prof
         echo "Generating documentation for GeoSPARQL 1.1 functions and rules"
         #pylode -i ../../1.1/funcsrules.ttl -o funcsrules.html -p vocpub
         #python3 ../../convertjsonld.py funcsrules.ttl funcsrules.json
         echo "Generating documentation for GeoSPARQL 1.1 Simple Features Vocabulary"
         pylode -i ../../1.1/sf_geometries.ttl -o sf_geometries.html -p vocpub
         python3 ../../convertjsonld.py sf_geometries.ttl sf_geometries.json
         echo "Generating documentation for GeoSPARQL 1.1 SA functions"
         pylode -i ../../1.1/reqs.ttl -o reqs.html -p vocpub
         #pylode -u http://schemas.opengis.net/gml/3.2.1/gml_32_geometries.rdf -o gml_geometries.html -p vocpub
         #pylode -i ../../1.1/validation.ttl -o validation.html
         echo "Generating documentation for GeoSPARQL 1.1 Service Description Extensions"
         pylode -i ../../1.1/servicedescription/servicedescription_extensions.ttl -o servicedescription_extensions.html -p vocpub
         python3 ../../convertjsonld.py servicedescription_extensions.ttl servicedescription_extensions.json
         echo "Generating documentation for GeoSPARQL 1.1 Service Conformance Classes"
         pylode -i ../../1.1/servicedescription/servicedescription_conformanceclasses.ttl -o servicedescription_conformanceclasses.html -p vocpub
         python3 ../../convertjsonld.py servicedescription_conformanceclasses.ttl servicedescription_conformanceclasses.json
         echo "Generating documentation for GeoSPARQL 1.0 Service Description All Functions"
         pylode -i ../../1.1/servicedescription/servicedescription_all_functions.ttl -o servicedescription_all_functions.html -p vocpub
         python3 ../../convertjsonld.py servicedescription_all_functions.ttl servicedescription_all_functions.json
    - name: Run the build process with Docker
      uses: addnab/docker-run-action@v3
      with:
              image: metanorma/metanorma
              options: -v "${pwd}":/metanorma/ -w /metanorma metanorma/metanorma
              run: |
                  metanorma compile -t ogc -x pdf,html 00-GeoSPARQL.adoc 
    - name: Deploy ðŸš€
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         BRANCH: gh-pages
         FOLDER: docs/
